### ISSUE TITLE
Orthography profile

### ISSUE THREAD

**Issue by chrzyki** [lexibank/kraftchadic#3]
We've had this old profile:

https://github.com/lexibank/kraftchadic/blob/master/etc/orthography.tsv

Which has got a number of problems:

https://github.com/lexibank/kraftchadic/blob/master/TRANSCRIPTION.md and https://github.com/lexibank/kraftchadic/commit/09605838bad5d4f8db4d67ec50712c538e667d9a. Should we keep it and update it or release without, for now?

**Comment by LinguList** [comment]
We should add a new profile. Who's the patron of this dataset? @tresoldi could you look into this? Or @chrzyki ?

**Comment by tresoldi** [comment]
I can, but what would be deadline?

It also brings back the topic of how to segment tonal languages which are not SEA, where we tend to have only one contrast. Should the general principle be something like ```"à/a"```?

**Comment by LinguList** [comment]
If they have regular tone, clts accepts this, right? I do not have strong opinions here, I just do `á/a` if it's not clear whether it's tone or not. But there's no particular deadline, just would be good to split work, as I just added some more orthoprofiles (tryonsolomon), so that we can slowly increase the number of data with segments for our purpose of global comparison.

**Comment by tresoldi** [comment]
Ok, I'll take care of it.

**Comment by tresoldi** [comment]
I have taken a long look at that, hoping to able to finish it today, it is a bit harder than expected (bibliographic work will also be needed). I will put it in my todo list and work on that in the following weeks.

**Comment by LinguList** [comment]
Important: don't feel pressured to add this immediately, it's just an encouragement for everybody who's patron of a segmentable dataset in cldf, to work on this, to increase the amount of segmented data. There' s no urgency, but I would like every patron (and you'd be that for kraft, I suggest) should think of how and when things can be enhanced...

**Comment by tresoldi** [comment]
It was more about time management, as I noticed the problem was not the profile creation but my knowledge of the languages (which got me into bibliographic research etc.). It seemed a better idea to get back to the segmentation of WOLD, which is now over half done.

But I've added it the todo list, better than just have a vague idea "I should do it sometime" :wink:

**Comment by SimonGreenhill** [comment]
Closed, thanks @tresoldi !

**Comment by SimonGreenhill** [comment]
(I said I'd closed this, but obviously I didn't. 🥇
